- .gitignore
- profilers/attachments/gemTemplate.c
- profilers/gemProfiler.py
Add gem5 profiler and template
> Add gem5 profiler

- src/bulbul.py
- remove some debug prints
- add some information prints for user
> Edit bulbul prints

- profilers/attachments/perfTemplate.c
- profilers/perfProfiler.py
- add new tracking values: cpu ticks and instruction count
- reduced number of test's launches to 1
> Rework perf profiler

- .gitignore
- config.json
- src/aggregate.py
- src/analyze.py
- src/builder.py
- src/configurator.py
- src/controller.py
- src/summarize.py
- src/utility.py
add protocol IUtility, add parsers for utilities
add basic logic for aggregator, simple refactor code
> Add features to aggregate

- src/aggregate.py
- src/analyze.py
- src/generate.py
- change out dir mechanic for tools
- small rework aggregate
> Edit out dirs

- src/blocks_rendering.py
- src/generate.py
> Add code generator

- .gitignore
- profilers/attachments/gemTemplate.c
- profilers/gemProfiler.py
- src/analyze.py
- src/builder.py
Add building and running options for gem5
> feat: add building and running options for gem5

- profilers/perfProfiler.py
- add timeout for perfProfiler
It works really bad, but work
> Add timeout for perfProfiler

- profilers/perfProfiler.py
Now the perf profiler works more secure
> Add capabilities for perf

- .github/dependabot.yml
> Add dependabot config for pip dependencies

- .github/workflows/github-actions.yml
> Update actions/checkout to v4

- .github/workflows/github-actions.yml
- README.md
- config.json
- configs/perf.json
- configs/test.json
- profilers/attachments/perfTemplate.c
- profilers/gemProfiler.py
- profilers/perfProfiler.py
- requirements.txt
- src/aggregate.py
- src/analyze.py
- src/blocks_rendering.py
- src/builder.py
- src/generate.py
- src/summarize.py
- Update requirements
- Fix bugs with python exceptions 
- Implement summarize (raw version)
- Add hard limit on test execution with timeout tool
- Format code
- Other small fixes
> Clean up code, fix bugs, implement summarize

- profilers/attachments/perfTemplate.c
Fix possible error with SIGINT in `fin()` functuion
> Perf asyn signal

- profilers/gemProfiler.py
Fix #39:
- removed request for superuser rights
- added check of full run of test
- added possibility of custom arguments for simulation gem5 script
- small fixes and refactors
> Update gem5 profiler

- src/analyzers/collectors/perfParser.py
- src/analyzers/patchers/__init__.py
- src/analyzers/patchers/attachments/gemTemplate.c
- src/analyzers/patchers/attachments/perfTemplate.c
- src/analyzers/patchers/attachments/perf_events/classic.c
- src/analyzers/patchers/attachments/perf_events/cortex-a72.c
- src/analyzers/patchers/basePatcher.py
- src/analyzers/patchers/gemPatcher.py
- src/analyzers/patchers/perfPatcher.py
- edit templates for analyzers
- rewrite patcher (resolve #63) 
- add template for cortex-a72 (resolve #65)
> Add raspberry support

- src/cli/aggregate.py
- src/cli/summarize.py
Done:
- async analyze launch (resolve #57)
- more meaningful names for files (config-name + date)
- some refactor at summarize
> Async analyze launch

- src/cli/aggregate.py
- src/cli/analyze.py
- src/cli/generate.py
- src/cli/summarize.py
- rename cl arguments: `_` -> `-` (resolve #72)
> Rename cl arguments

- src/cli/summarize.py
> Fix saving graph

- src/generators/code_gen.py
Resolve #55 
Add switch-case construction
> feat:Add switch/case blocks generation

- requirements.txt
- src/cli/aggregate.py
- src/cli/summarize.py
- src/helpers/configurator.py
- src/helpers/controller.py
- src/protocols/queueCollector.py
Run pre-commit manually to fix formatting of the project
> fix(linter): code formatting

- src/generators/code_gen.py
Add function's definitions and calls to test generation
Solve #108
> feat: add generation of functions

- src/generators/code_gen.py
Make docs for last update in code_gen.py
> docs: make docs for classes FuncBlock and DefineFunctionBlock, for methods __gen_def_funcs and __gen_func_call and update docs for switch-case

- README.md
- src/cli/aggregate.py
- src/cli/analyze.py
- src/cli/generate.py
- src/cli/summarize.py
> Add Multi-command execution info to README and add technical docs to Utilities

- README.md
- docs/usage/Aggregate.md
- docs/usage/Analyze.md
- docs/usage/Generate.md
- docs/usage/Summarize.md
- Add full documentation for each Utility
- Fix log-level setup incorrect instruction in README
- Fix lost link to Actions badge in README due to change of GitHub Actions structure
> Fix small README misinformation and add full documentations for each Utility 

- src/generators/code_gen.py
> feat: add generation functions call by pointer

- src/cli/generate.py
- src/generators/code_gen.py
- src/helpers/controller.py
- tests/cli/test_generate.py
Seed based generation added and and corresponding tests changed
> Seed based generation
